import { EventTypeMap } from 'types/api';

export const eventTypeMap: EventTypeMap = {
  AddressMigration: null,
  AddressRegister: 'string_event',
  AddressUnregister: null,
  ChainSwap: 'transaction_settle_event',
  ContractDeploy: 'string_event',
  ContractUpgrade: 'string_event',
  Crowdsale: 'sale_event',
  CrownRewards: 'token_event',
  Custom: null,
  FileCreate: 'hash_event',
  FileDelete: 'hash_event',
  GasEscrow: 'gas_event',
  GasPayment: 'gas_event',
  Inflation: null,
  Infusion: 'infusion_event',
  Log: null,
  OrderBid: 'market_event',
  OrderCancelled: 'market_event',
  OrderCreated: 'market_event',
  OrderFilled: 'market_event',
  OrganizationAdd: 'organization_event',
  OrganizationCreate: 'string_event',
  OrganizationRemove: 'organization_event',
  OwnerAdded: null,
  OwnerRemoved: null,
  PlatformCreate: 'string_event',
  TokenBurn: 'token_event',
  TokenClaim: 'token_event',
  TokenCreate: 'string_event',
  TokenMint: 'token_event',
  TokenReceive: 'token_event',
  TokenSend: 'token_event',
  TokenStake: 'token_event',
  ValidatorElect: 'address_event',
  ValidatorRemove: null,
  ValueCreate: 'chain_event',
  ValueUpdate: 'chain_event',
};
